package com.massfords.jaxb.codegen.creators;

import com.massfords.jaxb.codegen.CodeGenOptions;
import com.sun.codemodel.JAnnotationUse;
import com.sun.codemodel.JDefinedClass;
import jakarta.annotation.Generated;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
public final class CodeCreator {
    static void annotateGenerated(JDefinedClass output, CodeGenOptions options) {
        JAnnotationUse annotationUse = options.isUseLegacyImports() ?
                output.annotate(javax.annotation.Generated.class) :
                output.annotate(Generated.class);
        annotationUse.param("value", "Generated by jaxb-visitor");
    }
}
