package org.example.visitor;

import javax.annotation.Generated;

@Generated("Generated by jaxb-visitor")
public interface TraversingVisitorProgressMonitor {


    void visited(Object aVisitable);

    void traversed(Object aVisitable);

}
