package org.example.visitor;

import jakarta.annotation.Generated;

import org.example.imported.ImportedData;
import org.example.imported.ImportedType;
import org.example.simple.ChoiceElement;
import org.example.simple.ComplexObject;
import org.example.simple.HasJAXBElement;
import org.example.simple.Problem;
import org.example.simple.Recursive;
import org.example.simple.TSimpleRequest;
import org.example.simple.TSimpleResponse;

@Generated("Generated by jaxb-visitor")
public class BaseVisitor<R, E extends Throwable, A>
        implements Visitor<R, E, A> {


    @Override
    public R visit(ImportedData aBean, A arg)
            throws E {
        return null;
    }

    @Override
    public R visit(ImportedType aBean, A arg)
            throws E {
        return null;
    }

    @Override
    public R visit(ImportedType.Message aBean, A arg)
            throws E {
        return null;
    }

    @Override
    public R visit(ChoiceElement aBean, A arg)
            throws E {
        return null;
    }

    @Override
    public R visit(ComplexObject aBean, A arg)
            throws E {
        return null;
    }

    @Override
    public R visit(ComplexObject.LocalElement aBean, A arg)
            throws E {
        return null;
    }

    @Override
    public R visit(HasJAXBElement aBean, A arg)
            throws E {
        return null;
    }

    @Override
    public R visit(Problem aBean, A arg)
            throws E {
        return null;
    }

    @Override
    public R visit(Recursive aBean, A arg)
            throws E {
        return null;
    }

    @Override
    public R visit(TSimpleRequest aBean, A arg)
            throws E {
        return null;
    }

    @Override
    public R visit(TSimpleResponse aBean, A arg)
            throws E {
        return null;
    }

}
