package org.example.visitor;

import jakarta.annotation.Generated;
import org.example.imported.ImportedData;
import org.example.imported.ImportedType;
import org.example.simple.ChoiceElement;
import org.example.simple.ComplexObject;
import org.example.simple.HasJAXBElement;
import org.example.simple.Problem;
import org.example.simple.Recursive;
import org.example.simple.TSimpleRequest;
import org.example.simple.TSimpleResponse;

@Generated("Generated by jaxb-visitor")
public interface Visitor<R, E extends Throwable, A> {


    R visit(ImportedData aBean, A arg)
            throws E
            ;

    R visit(ImportedType aBean, A arg)
            throws E
            ;

    R visit(ImportedType.Message aBean, A arg)
            throws E
            ;

    R visit(ChoiceElement aBean, A arg)
            throws E
            ;

    R visit(ComplexObject aBean, A arg)
            throws E
            ;

    R visit(ComplexObject.LocalElement aBean, A arg)
            throws E
            ;

    R visit(HasJAXBElement aBean, A arg)
            throws E
            ;

    R visit(Problem aBean, A arg)
            throws E
            ;

    R visit(Recursive aBean, A arg)
            throws E
            ;

    R visit(TSimpleRequest aBean, A arg)
            throws E
            ;

    R visit(TSimpleResponse aBean, A arg)
            throws E
            ;

}
