package org.example.visitor;

import jakarta.annotation.Generated;

@Generated("Generated by jaxb-visitor")
public interface Visitable {


    <R, E extends Throwable, A> R accept(Visitor<R, E, A> aVisitor, A arg)
            throws E
            ;

}
