package org.example.visitor;

import generated.AbstractBase;
import generated.BaseType;
import generated.DerivedA;
import generated.DerivedD;
import generated.PersistingOject;
import generated.TypeList;
import jakarta.annotation.Generated;

@Generated("Generated by jaxb-visitor")
public class BaseVisitor<R, E extends Throwable >
    implements Visitor<R, E>
{


    @Override
    public R visit(AbstractBase aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(BaseType aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(BaseType.Localisations aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(DerivedA aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(DerivedD aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(PersistingOject aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TypeList aBean)
        throws E
    {
        return null;
    }

}
