package org.example.visitor;

import generated.AbstractBase;
import generated.BaseType;
import generated.DerivedA;
import generated.DerivedD;
import generated.PersistingOject;
import generated.TypeList;
import jakarta.annotation.Generated;

@Generated("Generated by jaxb-visitor")
public interface Visitor<R, E extends Throwable >{


    R visit(AbstractBase aBean)
        throws E
    ;

    R visit(BaseType aBean)
        throws E
    ;

    R visit(BaseType.Localisations aBean)
        throws E
    ;

    R visit(DerivedA aBean)
        throws E
    ;

    R visit(DerivedD aBean)
        throws E
    ;

    R visit(PersistingOject aBean)
        throws E
    ;

    R visit(TypeList aBean)
        throws E
    ;

}
