package org.prostep.ecadif.vec113.visitor;

import jakarta.annotation.Generated;

import org.prostep.ecadif.vec113.VecContent;
import org.prostep.ecadif.vec113.VecDocumentVersion;
import org.prostep.ecadif.vec113.VecPartVersion;

@Generated("Generated by jaxb-visitor")
public class BaseVisitor<R, E extends Throwable>
        implements Visitor<R, E> {


    @Override
    public R visit(VecContent aBean)
            throws E {
        return null;
    }

    @Override
    public R visit(VecDocumentVersion aBean)
            throws E {
        return null;
    }

    @Override
    public R visit(VecPartVersion aBean)
            throws E {
        return null;
    }

}
