package org.example.visitor;

import jakarta.annotation.Generated;

import org.prostep.ecadif.vec113.VecContent;
import org.prostep.ecadif.vec113.VecDocumentVersion;
import org.prostep.ecadif.vec113.VecPartVersion;

@Generated("Generated by jaxb-visitor")
public class DepthFirstTraverserImpl<E extends Throwable>
        implements Traverser<E> {


    @Override
    public void traverse(VecContent aBean, Visitor<?, E> aVisitor)
            throws E {
        for (VecDocumentVersion bean : aBean.getDocumentVersions()) {
            bean.accept(aVisitor);
        }
        for (VecPartVersion bean : aBean.getPartVersions()) {
            bean.accept(aVisitor);
        }
    }

    @Override
    public void traverse(VecDocumentVersion aBean, Visitor<?, E> aVisitor)
            throws E {
    }

    @Override
    public void traverse(VecPartVersion aBean, Visitor<?, E> aVisitor)
            throws E {
    }

}
