package org.example.visitor;

import jakarta.annotation.Generated;

import org.prostep.ecadif.vec113.VecContent;
import org.prostep.ecadif.vec113.VecDocumentVersion;
import org.prostep.ecadif.vec113.VecPartVersion;

@Generated("Generated by jaxb-visitor")
public interface Visitor<R, E extends Throwable> {


    R visit(VecContent aBean)
            throws E
            ;

    R visit(VecDocumentVersion aBean)
            throws E
            ;

    R visit(VecPartVersion aBean)
            throws E
            ;

}
