package org.example.visitor;

import jakarta.annotation.Generated;

@Generated("Generated by jaxb-visitor")
public interface Visitable {


    <R, E extends Throwable> R accept(Visitor<R, E> aVisitor)
            throws E
            ;

}
